minimumReleaseAgeExclude:
  - '@expo/cli@57.0.12'
  - '@expo/router-server@57.0.5'
  - expo-constants@57.0.9
  - expo-modules-core@57.0.9
  - expo@57.0.10
  - expo-auth-session@57.0.6
  - expo-linking@57.0.5
  - '@expo/image-utils@0.11.5'
  - '@expo/require-utils@57.0.5'
