import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { User } from '@supabase/supabase-js';
import * as Linking from 'expo-linking';

import { supabase } from '../supabase';
import type { SleepProfile } from '../onboarding/types';
import OuraIntegration from '../oura/OuraIntegration';

const concernLabels: Record<string,string> = { falling_asleep:'Falling asleep', staying_asleep:'Staying asleep', waking_tired:'Waking refreshed', schedule:'A steadier schedule', stress:'Stress and recovery' };

export function ProgressScreen({ user }: { user: User }) {
  const [rows,setRows]=useState<{checkin_date:string;feeling:number}[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [commitments,setCommitments]=useState<{behavior_date:string;behavior:string;status:string}[]>([]);
  const load=useCallback(async()=>{setLoading(true);setError('');const [result, commitmentResult]=await Promise.all([supabase.from('daily_checkins').select('checkin_date, feeling').eq('user_id',user.id).order('checkin_date',{ascending:false}).limit(14),supabase.from('behavior_commitments').select('behavior_date, behavior, status').eq('user_id',user.id).order('behavior_date',{ascending:false}).limit(7)]);if(result.error)setError(result.error.message);else setRows(result.data ?? []);if(commitmentResult.error)setError(commitmentResult.error.message);else setCommitments(commitmentResult.data ?? []);setLoading(false);},[user.id]);
  useEffect(()=>{void load();},[load]);
  const average=rows.length?Math.round(rows.reduce((sum,row)=>sum+row.feeling,0)/rows.length):0;
  const tried=commitments.filter(item=>item.status==='completed'||item.status==='partial').length;
  return <ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>PROGRESS</Text><Text style={s.title}>Your sleep, in context</Text><Text style={s.copy}>Trends become more useful as you check in. We’ll focus on direction—not perfect scores.</Text>{loading?<ActivityIndicator color="#4f7cff"/>:<><View style={s.heroCard}><Text style={s.metric}>{rows.length}</Text><Text style={s.metricLabel}>check-ins recorded</Text>{rows.length>0&&<Text style={s.secondaryMetric}>Average feeling: {average}/100</Text>}<Text style={s.secondaryMetric}>Experiments tried: {tried}</Text></View>{commitments.length>0&&<View style={s.card}><Text style={s.cardEyebrow}>RECENT EXPERIMENTS</Text>{commitments.map(item=><View key={item.behavior_date} style={s.experimentRow}><View style={s.experimentCopy}><Text style={s.experimentDate}>{item.behavior_date}</Text><Text style={s.experimentBehavior}>{item.behavior}</Text></View><Text style={[s.experimentStatus,item.status==='completed'&&s.statusComplete,item.status==='partial'&&s.statusPartial]}>{item.status==='committed'?'Tonight':item.status==='completed'?'Done':item.status==='partial'?'Partly':'Skipped'}</Text></View>)}</View>}{rows.length===0?<Empty title="Your trend starts today" copy="Complete your first morning check-in and it will appear here."/>:rows.map(row=><View key={row.checkin_date} style={s.row}><Text style={s.rowDate}>{row.checkin_date}</Text><Text style={s.rowValue}>{row.feeling}/100</Text></View>)}</>}{!!error&&<Text style={s.error}>{error}</Text>}</ScrollView>;
}

export function SettingsScreen({ user, profile, busy, onSignOut, onDeleteAccount }: { user:User;profile:SleepProfile;busy:boolean;onSignOut:()=>void;onDeleteAccount:()=>void }) {
  return <ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>SETTINGS</Text><Text style={s.title}>{profile.displayName||'Your profile'}</Text><Text style={s.copy}>{user.email}</Text><View style={s.card}><Text style={s.cardEyebrow}>SLEEP PROFILE</Text><Setting label="Primary focus" value={concernLabels[profile.primaryConcern]}/><Setting label="Usual bedtime" value={profile.typicalBedtime||'Not set'}/><Setting label="Usual wake time" value={profile.typicalWakeTime||'Not set'}/><Setting label="Timezone" value={profile.timezone}/></View><View style={s.card}><Text style={s.cardEyebrow}>INTEGRATIONS</Text><Text style={s.cardTitle}>Oura connection</Text><OuraIntegration /></View><Pressable onPress={()=>void Linking.openURL('https://30daysleepcoach.com/privacy.html')} style={s.button}><Text style={s.buttonText}>Privacy policy</Text></Pressable><Pressable disabled={busy} onPress={onSignOut} style={s.button}><Text style={s.buttonText}>Sign out</Text></Pressable><Pressable disabled={busy} onPress={onDeleteAccount} style={[s.button,s.dangerButton]}><Text style={s.dangerText}>Delete account</Text></Pressable></ScrollView>;
}

function Setting({label,value}:{label:string;value:string}){return <View style={s.setting}><Text style={s.settingLabel}>{label}</Text><Text style={s.settingValue}>{value}</Text></View>}
function Empty({title,copy}:{title:string;copy:string}){return <View style={s.card}><Text style={s.cardTitle}>{title}</Text><Text style={s.cardCopy}>{copy}</Text></View>}
const s=StyleSheet.create({content:{padding:20,paddingBottom:48,paddingTop:64},eyebrow:{color:'#4f7cff',fontSize:12,fontWeight:'800',letterSpacing:1.8,marginBottom:8},title:{color:'#24212d',fontSize:30,fontWeight:'800',letterSpacing:-.8},copy:{color:'#716d7d',fontSize:15,lineHeight:22,marginBottom:24,marginTop:8},heroCard:{backgroundColor:'#4f7cff',borderRadius:24,marginBottom:14,padding:22},heroEyebrow:{color:'#dbe5ff',fontSize:11,fontWeight:'800',letterSpacing:1.3,marginBottom:8},heroTitle:{color:'#fff',fontSize:22,fontWeight:'800',lineHeight:28},heroLabel:{color:'#dbe5ff',fontSize:10,fontWeight:'800',letterSpacing:1.1,marginTop:20},heroCopy:{color:'#fff',fontSize:15,fontWeight:'600',lineHeight:22,marginTop:7},metric:{color:'#fff',fontSize:46,fontWeight:'800'},metricLabel:{color:'#dbe5ff',fontSize:15,fontWeight:'700'},secondaryMetric:{color:'#fff',fontSize:16,fontWeight:'800',marginTop:18},card:{backgroundColor:'#fff',borderColor:'#e8e4ec',borderRadius:22,borderWidth:1,marginBottom:14,padding:20},cardEyebrow:{color:'#4f7cff',fontSize:11,fontWeight:'800',letterSpacing:1.3,marginBottom:8},cardTitle:{color:'#2d2934',fontSize:20,fontWeight:'800'},cardCopy:{color:'#716d7d',fontSize:14,lineHeight:21,marginTop:8},coachNote:{backgroundColor:'#f0f4ff',borderRadius:12,color:'#3d6ae8',fontSize:13,lineHeight:19,marginTop:14,padding:12},experimentRow:{alignItems:'flex-start',borderTopColor:'#eeeaf0',borderTopWidth:1,flexDirection:'row',gap:10,paddingVertical:13},experimentCopy:{flex:1},experimentDate:{color:'#918c99',fontSize:10,fontWeight:'700'},experimentBehavior:{color:'#34303c',fontSize:13,fontWeight:'700',lineHeight:18,marginTop:3},experimentStatus:{backgroundColor:'#f1eff4',borderRadius:10,color:'#716d7d',fontSize:10,fontWeight:'800',overflow:'hidden',paddingHorizontal:8,paddingVertical:5},statusComplete:{backgroundColor:'#e8f7ee',color:'#267447'},statusPartial:{backgroundColor:'#fff4dc',color:'#8a6218'},row:{backgroundColor:'#fff',borderBottomColor:'#ece8ef',borderBottomWidth:1,flexDirection:'row',justifyContent:'space-between',padding:16},rowDate:{color:'#4d4855',fontWeight:'700'},rowValue:{color:'#4f7cff',fontWeight:'800'},error:{color:'#a53434',marginTop:12},disclaimer:{color:'#898491',fontSize:12,lineHeight:18,marginTop:12,textAlign:'center'},setting:{borderBottomColor:'#eeeaf0',borderBottomWidth:1,paddingVertical:13},settingLabel:{color:'#85808e',fontSize:12},settingValue:{color:'#34303c',fontSize:15,fontWeight:'700',marginTop:3},button:{alignItems:'center',backgroundColor:'#fff',borderColor:'#ded9e3',borderRadius:16,borderWidth:1,marginTop:10,padding:16},buttonText:{color:'#4e4955',fontSize:15,fontWeight:'800'},dangerButton:{borderColor:'#efcaca'},dangerText:{color:'#a53434',fontSize:15,fontWeight:'800'}});
