-- The evolving sleep profile is generated by an Anthropic call, so it is stored
-- and reused until the underlying check-ins, experiments, or wearable nights
-- change. One row per user; the fingerprint decides when it is stale.
create table if not exists public.coach_profile_summaries (
  user_id uuid primary key references auth.users(id) on delete cascade,
  summary text not null,
  source_fingerprint text not null,
  prompt_version text not null,
  model text,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.coach_profile_summaries enable row level security;

create policy "Users can read their coach profile summary"
  on public.coach_profile_summaries
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their coach profile summary"
  on public.coach_profile_summaries
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their coach profile summary"
  on public.coach_profile_summaries
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete their coach profile summary"
  on public.coach_profile_summaries
  for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on public.coach_profile_summaries from anon;
grant select, insert, update, delete on public.coach_profile_summaries to authenticated;
